//
// Created by Marc Charbonneau on 6/8/17.
//

#ifndef QUEUETEMPLATEEXCEPTION_EXCEPTHANDLER_H
#define QUEUETEMPLATEEXCEPTION_EXCEPTHANDLER_H


class ExceptHandler {

};


#endif //QUEUETEMPLATEEXCEPTION_EXCEPTHANDLER_H
